### ISSUE TITLE
Move current subcommands to be under `nvc` subcommand

### ISSUE THREAD

**Issue by sector-f** [sector-f/jhmod#20]
I.e. change `jhmod create` to `jhmod nvc create`, `jhmod extract` to `jhmod nvc extract`, etc. This will clear up the main command "namespace" so that we can add in additional subcommands (e.g. subcommands for working with save files) without things getting confusing

**Comment by winny-** [comment]
LGTM :boom:

**Comment by sector-f** [comment]
Resolved by #23
